-- Test Jobs für die Anwendung
-- Diese SQL-Statements erstellen 5 Test-Jobs mit allen notwendigen Daten

-- Zuerst eine Test-Company erstellen (falls nicht vorhanden)
INSERT INTO companies (id, name, description, website, logo_url, industry, size, location, created_at, updated_at)
VALUES (
  'test-company-1',
  'TechCorp GmbH',
  'Ein innovatives Technologieunternehmen, das sich auf digitale Lösungen spezialisiert hat.',
  'https://techcorp.de',
  'https://via.placeholder.com/100x100/4F46E5/FFFFFF?text=TC',
  'Technology',
  '50-200',
  'Berlin',
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

-- Test Job 1: Frontend Developer
INSERT INTO job_posts (
  id,
  company_id,
  title,
  job_type,
  team_department,
  role_family,
  description,
  work_mode,
  city,
  country,
  address_street,
  address_zip,
  employment_type,
  hours_per_week_min,
  hours_per_week_max,
  salary_currency,
  salary_min,
  salary_max,
  salary_interval,
  tasks_description,
  requirements_description,
  benefits_description,
  languages_required,
  skills_required,
  is_public,
  is_active,
  is_draft,
  published_at,
  created_at,
  updated_at
) VALUES (
  'test-job-1',
  'test-company-1',
  'Frontend Developer (React/TypeScript)',
  'professional',
  'Engineering',
  'Development',
  '<p>Wir suchen einen erfahrenen Frontend Developer, der sich mit modernen Web-Technologien auskennt und leidenschaftlich für sauberen Code ist.</p><p>In unserem dynamischen Team arbeitest du an spannenden Projekten und trägst zur Weiterentwicklung unserer digitalen Produkte bei.</p>',
  'hybrid',
  'Berlin',
  'Deutschland',
  'Unter den Linden 1',
  '10117',
  'fulltime',
  35,
  40,
  'EUR',
  4500,
  6500,
  'month',
  'Entwicklung von benutzerfreundlichen Web-Anwendungen mit React und TypeScript\nOptimierung der Performance und User Experience\nZusammenarbeit mit Designern und Backend-Entwicklern\nCode-Reviews und Mentoring von Junior-Entwicklern\nImplementierung von modernen Frontend-Architekturen',
  'Abgeschlossenes Studium in Informatik oder vergleichbare Qualifikation\nMindestens 3 Jahre Erfahrung mit React und TypeScript\nKenntnisse in modernen CSS-Frameworks (Tailwind, Styled Components)\nErfahrung mit State Management (Redux, Zustand)\nGute Kenntnisse in Git und agilen Entwicklungsmethoden\nEnglischkenntnisse in Wort und Schrift',
  'Flexible Arbeitszeiten und Homeoffice-Möglichkeiten\nModerne Arbeitsplätze in zentraler Lage\nWeiterbildungsbudget und Konferenzbesuche\nBetriebliche Altersvorsorge\nFitnessstudio-Mitgliedschaft\nTeam-Events und regelmäßige Firmenfeiern',
  '["Deutsch", "Englisch"]',
  '["React", "TypeScript", "JavaScript", "CSS", "HTML", "Git", "Webpack", "Jest"]',
  true,
  true,
  false,
  NOW(),
  NOW(),
  NOW()
);

-- Test Job 2: Marketing Manager
INSERT INTO job_posts (
  id,
  company_id,
  title,
  job_type,
  team_department,
  role_family,
  description,
  work_mode,
  city,
  country,
  address_street,
  address_zip,
  employment_type,
  hours_per_week_min,
  hours_per_week_max,
  salary_currency,
  salary_min,
  salary_max,
  salary_interval,
  tasks_description,
  requirements_description,
  benefits_description,
  languages_required,
  skills_required,
  is_public,
  is_active,
  is_draft,
  published_at,
  created_at,
  updated_at
) VALUES (
  'test-job-2',
  'test-company-1',
  'Marketing Manager (Digital Marketing)',
  'professional',
  'Marketing',
  'Management',
  '<p>Als Marketing Manager bist du verantwortlich für die Entwicklung und Umsetzung unserer digitalen Marketingstrategien.</p><p>Du arbeitest eng mit verschiedenen Teams zusammen und trägst maßgeblich zum Wachstum unseres Unternehmens bei.</p>',
  'remote',
  'Remote',
  'Deutschland',
  '',
  '',
  'fulltime',
  35,
  40,
  'EUR',
  4000,
  5500,
  'month',
  'Entwicklung und Umsetzung von digitalen Marketingkampagnen\nVerwaltung von Social Media Kanälen und Content-Erstellung\nAnalyse von Marketing-KPIs und Optimierung der Strategien\nZusammenarbeit mit externen Agenturen und Partnern\nPlanung und Durchführung von Marketing-Events',
  'Studium in Marketing, Kommunikation oder verwandten Bereichen\nMindestens 2 Jahre Erfahrung im digitalen Marketing\nKenntnisse in Google Analytics, Facebook Ads und Google Ads\nErfahrung mit Content Management Systemen\nKreative Denkweise und analytische Fähigkeiten\nSehr gute Deutsch- und Englischkenntnisse',
  'Vollständig remote möglich\nFlexible Arbeitszeiten\nWeiterbildungsbudget\nModerne Arbeitsausstattung\nBetriebliche Altersvorsorge\nGesundheitszuschuss',
  '["Deutsch", "Englisch"]',
  '["Digital Marketing", "Social Media", "Google Analytics", "Content Marketing", "SEO", "SEM", "Email Marketing"]',
  true,
  true,
  false,
  NOW(),
  NOW(),
  NOW()
);

-- Test Job 3: Data Analyst
INSERT INTO job_posts (
  id,
  company_id,
  title,
  job_type,
  team_department,
  role_family,
  description,
  work_mode,
  city,
  country,
  address_street,
  address_zip,
  employment_type,
  hours_per_week_min,
  hours_per_week_max,
  salary_currency,
  salary_min,
  salary_max,
  salary_interval,
  tasks_description,
  requirements_description,
  benefits_description,
  languages_required,
  skills_required,
  is_public,
  is_active,
  is_draft,
  published_at,
  created_at,
  updated_at
) VALUES (
  'test-job-3',
  'test-company-1',
  'Data Analyst (Business Intelligence)',
  'professional',
  'Analytics',
  'Analysis',
  '<p>Wir suchen einen Data Analyst, der uns dabei hilft, aus unseren Daten wertvolle Erkenntnisse zu gewinnen.</p><p>Du arbeitest mit großen Datenmengen und entwickelst innovative Lösungen für datengetriebene Entscheidungen.</p>',
  'onsite',
  'München',
  'Deutschland',
  'Maximilianstraße 10',
  '80539',
  'fulltime',
  35,
  40,
  'EUR',
  4200,
  5800,
  'month',
  'Analyse von Geschäftsdaten und Erstellung von Reports\nEntwicklung von Dashboards und Visualisierungen\nDatenqualitätssicherung und -bereinigung\nZusammenarbeit mit verschiedenen Abteilungen\nPräsentation von Ergebnissen und Empfehlungen',
  'Studium in Mathematik, Statistik, Informatik oder verwandten Bereichen\nErfahrung mit SQL und Datenbanken\nKenntnisse in Python oder R\nErfahrung mit BI-Tools (Tableau, Power BI)\nStarke analytische und problemlösende Fähigkeiten\nGute Kommunikationsfähigkeiten',
  'Moderne Büros in München\nFlexible Arbeitszeiten\nWeiterbildungsmöglichkeiten\nBetriebliche Altersvorsorge\nÖPNV-Ticket\nMitarbeiterrabatte',
  '["Deutsch", "Englisch"]',
  '["SQL", "Python", "R", "Tableau", "Power BI", "Excel", "Statistics", "Data Visualization"]',
  true,
  true,
  false,
  NOW(),
  NOW(),
  NOW()
);

-- Test Job 4: UX/UI Designer
INSERT INTO job_posts (
  id,
  company_id,
  title,
  job_type,
  team_department,
  role_family,
  description,
  work_mode,
  city,
  country,
  address_street,
  address_zip,
  employment_type,
  hours_per_week_min,
  hours_per_week_max,
  salary_currency,
  salary_min,
  salary_max,
  salary_interval,
  tasks_description,
  requirements_description,
  benefits_description,
  languages_required,
  skills_required,
  is_public,
  is_active,
  is_draft,
  published_at,
  created_at,
  updated_at
) VALUES (
  'test-job-4',
  'test-company-1',
  'UX/UI Designer (Digital Products)',
  'professional',
  'Design',
  'Creative',
  '<p>Als UX/UI Designer gestaltest du die Benutzeroberflächen unserer digitalen Produkte und sorgst für eine optimale User Experience.</p><p>Du arbeitest eng mit Entwicklern und Produktmanagern zusammen und bringst kreative Ideen ein.</p>',
  'hybrid',
  'Hamburg',
  'Deutschland',
  'Speicherstadt 1',
  '20457',
  'fulltime',
  35,
  40,
  'EUR',
  3800,
  5200,
  'month',
  'Entwicklung von User Experience Konzepten\nErstellung von Wireframes und Prototypen\nDesign von Benutzeroberflächen und Interaktionen\nDurchführung von Usability-Tests\nZusammenarbeit mit Entwicklern bei der Umsetzung',
  'Studium in Design, Kommunikationsdesign oder verwandten Bereichen\nErfahrung mit Design-Tools (Figma, Sketch, Adobe Creative Suite)\nKenntnisse in UX-Design-Prinzipien\nErfahrung mit Prototyping-Tools\nKreative Denkweise und Auge für Details\nPortfolio mit relevanten Projekten',
  'Kreative Arbeitsumgebung\nFlexible Arbeitszeiten\nDesign-Tools und Hardware\nWeiterbildungsbudget\nBetriebliche Altersvorsorge\nTeam-Events',
  '["Deutsch", "Englisch"]',
  '["Figma", "Sketch", "Adobe Creative Suite", "Prototyping", "User Research", "Wireframing", "Visual Design"]',
  true,
  true,
  false,
  NOW(),
  NOW(),
  NOW()
);

-- Test Job 5: Sales Manager
INSERT INTO job_posts (
  id,
  company_id,
  title,
  job_type,
  team_department,
  role_family,
  description,
  work_mode,
  city,
  country,
  address_street,
  address_zip,
  employment_type,
  hours_per_week_min,
  hours_per_week_max,
  salary_currency,
  salary_min,
  salary_max,
  salary_interval,
  tasks_description,
  requirements_description,
  benefits_description,
  languages_required,
  skills_required,
  is_public,
  is_active,
  is_draft,
  published_at,
  created_at,
  updated_at
) VALUES (
  'test-job-5',
  'test-company-1',
  'Sales Manager (B2B Software)',
  'professional',
  'Sales',
  'Management',
  '<p>Wir suchen einen erfahrenen Sales Manager, der unser B2B-Software-Geschäft vorantreibt und neue Kunden gewinnt.</p><p>Du arbeitest in einem dynamischen Team und hast die Möglichkeit, deine Karriere bei uns weiterzuentwickeln.</p>',
  'onsite',
  'Frankfurt',
  'Deutschland',
  'Zeil 1',
  '60313',
  'fulltime',
  35,
  40,
  'EUR',
  5000,
  7000,
  'month',
  'Akquisition neuer B2B-Kunden\nBetreuung bestehender Kunden und Account Management\nEntwicklung von Verkaufsstrategien\nDurchführung von Präsentationen und Verhandlungen\nZusammenarbeit mit Marketing und Produktentwicklung',
  'Studium in BWL, Marketing oder verwandten Bereichen\nMindestens 3 Jahre Erfahrung im B2B-Verkauf\nErfahrung mit CRM-Systemen (Salesforce, HubSpot)\nStarke Kommunikations- und Verhandlungsfähigkeiten\nErfolgreiche Verkaufsabschlüsse nachweisbar\nReisebereitschaft',
  'Attraktive Provisionen und Boni\nFirmenwagen oder Mobilitätsbudget\nFlexible Arbeitszeiten\nWeiterbildungsmöglichkeiten\nBetriebliche Altersvorsorge\nRegelmäßige Team-Events',
  '["Deutsch", "Englisch"]',
  '["B2B Sales", "CRM", "Negotiation", "Account Management", "Lead Generation", "Presentation Skills"]',
  true,
  true,
  false,
  NOW(),
  NOW(),
  NOW()
);

-- Zusätzliche Test-Company für mehr Vielfalt
INSERT INTO companies (id, name, description, website, logo_url, industry, size, location, created_at, updated_at)
VALUES (
  'test-company-2',
  'StartupXYZ',
  'Ein aufstrebendes Startup im Bereich Fintech mit innovativen Lösungen.',
  'https://startupxyz.de',
  'https://via.placeholder.com/100x100/10B981/FFFFFF?text=SX',
  'Fintech',
  '10-50',
  'Berlin',
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

-- Test Job 6: Product Manager (von anderer Firma)
INSERT INTO job_posts (
  id,
  company_id,
  title,
  job_type,
  team_department,
  role_family,
  description,
  work_mode,
  city,
  country,
  address_street,
  address_zip,
  employment_type,
  hours_per_week_min,
  hours_per_week_max,
  salary_currency,
  salary_min,
  salary_max,
  salary_interval,
  tasks_description,
  requirements_description,
  benefits_description,
  languages_required,
  skills_required,
  is_public,
  is_active,
  is_draft,
  published_at,
  created_at,
  updated_at
) VALUES (
  'test-job-6',
  'test-company-2',
  'Product Manager (Fintech)',
  'professional',
  'Product',
  'Management',
  '<p>Als Product Manager bei StartupXYZ entwickelst du innovative Fintech-Lösungen und trägst zur digitalen Transformation der Finanzbranche bei.</p><p>Du arbeitest in einem agilen Umfeld und hast direkten Einfluss auf die Produktentwicklung.</p>',
  'hybrid',
  'Berlin',
  'Deutschland',
  'Potsdamer Platz 1',
  '10785',
  'fulltime',
  35,
  40,
  'EUR',
  5500,
  7500,
  'month',
  'Entwicklung von Produktstrategien und Roadmaps\nZusammenarbeit mit Engineering und Design Teams\nMarktanalyse und Wettbewerbsbeobachtung\nKoordination von Produktlaunches\nKundenfeedback sammeln und analysieren',
  'Studium in BWL, Informatik oder verwandten Bereichen\nMindestens 2 Jahre Erfahrung im Product Management\nErfahrung im Fintech-Bereich von Vorteil\nKenntnisse in agilen Entwicklungsmethoden\nStarke analytische und kommunikative Fähigkeiten\nEnglischkenntnisse erforderlich',
  'Startup-Atmosphäre mit flachen Hierarchien\nFlexible Arbeitszeiten und Homeoffice\nAktienoptionen\nWeiterbildungsbudget\nModerne Arbeitsausstattung\nRegelmäßige Team-Events',
  '["Deutsch", "Englisch"]',
  '["Product Management", "Agile", "Fintech", "Analytics", "User Research", "Roadmapping"]',
  true,
  true,
  false,
  NOW(),
  NOW(),
  NOW()
);
